---
title: "scRNAseq_report"
author: "Dr. S. Virdi"
date: "..."
output:  
  html_document:
    toc: true
---

```{=html}
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(dplyr)
library(gdata)
library(ggplot2)
library(ggrepel)
library(cowplot)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(clusterProfiler)
library(SummarizedExperiment)
library(BiocParallel)
library(magrittr)
library(tidyr)
library(patchwork)
library(viridis)
library(pheatmap)
library(htmlwidgets)
library(DT)
options(future.globals.maxSize = 1e9)
options(Seurat.object.assay.version = "v5")

```
## {.tabset}

### QC
```{r echo=FALSE, fig.height=7, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

counts_dir1_10x <- ".../outs/filtered_feature_bc_matrix/"
counts_dir2_10x <- ".../outs/filtered_feature_bc_matrix/"

counts_dir <- c(counts_dir1_10x,counts_dir2_10x)

obj_list <- list()
qc_plot <- list()

for (i in 1:2){

nraw_counts <- Read10X(data.dir = counts_dir[i])
n = paste0("condition_",i)

#total cell count
summary(colSums(nraw_counts))

#  Create seuart object
s1_SO<- CreateSeuratObject(counts = nraw_counts, min.cells = 10, min.features = 200, project = paste0(n,"_10x_scRNAseq"))
s1_SO[["percent.mt"]] <- PercentageFeatureSet(s1_SO, pattern = "MT-")

#VlnPlot(s1_SO, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

filt1 <- quantile(apply(s1_SO[["RNA"]]$counts, 2, function(x) sum(x > 0)), c(.25, .50,  .75, .90, .99))
filt2 <- quantile(apply(s1_SO[["RNA"]]$counts, 2, function(x) sum(x)), c(.25, .50,  .75, .90, .99))

s1_SO <- subset(s1_SO, subset =  nFeature_RNA < filt1[5] & nCount_RNA < filt2[5] &  nCount_RNA > 1000 & percent.mt < 10)

obj_list[[i]] <- s1_SO

qc_plot[[i]]  <- VlnPlot(s1_SO, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)


}

qc_plot[[1]] | qc_plot[[2]]


ctrl <- obj_list[[1]]
ctrl$stim <- 'CTRL'
cond <- obj_list[[2]]
cond$stim <- 'STIM2'
obj <- merge(x = ctrl, y = cond)


obj@meta.data %>% 
    ggplot(aes(color=orig.ident, x=nCount_RNA, fill= orig.ident)) + 
    geom_density(alpha = 0.2) + 
    theme_classic() +
    scale_x_log10() + 
    geom_vline(xintercept = 1000,color="red",linetype="dotted")

```

### Dim reduction and clustering (UMAP)
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
#######################################
## SCTransform Harmony Integration ####
#######################################


#obj[["RNA"]] <- split(obj[["RNA"]], f = obj$stim)
obj_ <- SCTransform(obj, vars.to.regress = c("percent.mt"), vst.flavor = "v2", verbose = FALSE)
obj_sc <- RunPCA(obj_, npcs = 30, verbose = F)


obj_sc <- IntegrateLayers(object = obj_sc, method = HarmonyIntegration,
                       orig.reduction = "pca", new.reduction = 'harmony',
                       assay = "SCT", verbose = FALSE)
obj_sc1 <- FindNeighbors(obj_sc, reduction = "harmony", dims = 1:30)

# res 1.2 for original all cells counts
obj_sc2 <- FindClusters(obj_sc1, resolution = 1.2, cluster.name = "harmony_clusters")

#
obj_sc2 <- RunUMAP(obj_sc2, reduction = "harmony", dims = 1:30, reduction.name = "umap.harmony")

#tiff("All_UMAPnew3.tiff",units="in", width=16, height=8, res=150)
DimPlot(
  obj_sc2,
  reduction = "umap.harmony",
 # group.by = c("stim"),
  combine = FALSE, label = TRUE, pt.size = 0.6
)[[1]] &  theme(text = element_text(size = 5),
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y = element_blank(),aspect.ratio = 1) &  
        guides(color = guide_legend(override.aes = list(size=2,shape =18), keyheight = 0.2,keywidth = 0.5, ncol=2)) & 
        #ylim(-15,15) & xlim(-15,15)
        ylim(-10,10) & xlim(-10,10) 

DimPlot(
  obj_sc2,
  reduction = "umap.harmony",
  split.by = c("stim"),
  combine = FALSE, label = TRUE, pt.size = 0.6
)[[1]] &  theme(text = element_text(size = 5),
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y = element_blank(),aspect.ratio = 1) &  
        guides(color = guide_legend(override.aes = list(size=2,shape =18), keyheight = 0.2,keywidth = 0.5, ncol=2)) & 
        #ylim(-15,15) & xlim(-15,15)
        ylim(-10,10) & xlim(-10,10)
#dev.off()



########################## Markers ##################################

obj_t <- obj_sc2

DefaultAssay(obj_t) <- "RNA"
all.genes <- rownames(obj_t)
obj_t <- NormalizeData(obj_t)
#obj_t <- ScaleData(obj_t, features = all.genes,vars.to.regress = c("nCount_RNA", "percent.mt"))
obj_t <- JoinLayers(obj_t)

x <- as.numeric(levels(obj_t$seurat_clusters))
#x <- x[c(1:4)]
df <- data.frame()
for (i in 1:length(x)){
c.markers <- FindConservedMarkers(obj_t, ident.1 = x[i], grouping.var = "stim",verbose = FALSE,
                                    min.pct = 0.25, only.pos = TRUE, logfc.threshold = 0.25) # min.pct = .25 for all
c.markers <- c.markers[order(c.markers$CTRL_avg_log2FC,decreasing = TRUE),]
top10 <- c.markers %>% dplyr::top_n(n = 10, wt = CTRL_avg_log2FC)
print(paste0("finding markers for cluster ",i-1))
df <- bind_rows(df,top10)
}

DT::datatable(df,extensions = 'Buttons', filter = 'top', 
              options = list(pageLength = 100, scrollX = TRUE, scrollY = "600px", autoWidth = TRUE, dom = 'Bfrtip',
              buttons = list('copy', 'print', list(extend = 'collection',buttons = c('csv', 'excel'),text = 'Download'))))


```

### Cell marker heatmap
```{r echo=FALSE, fig.height=30, fig.width=24, message=FALSE, warning=FALSE, paged.print=FALSE}
#MS heatmap
#print(DoHeatmap(obj_t,features = rownames(df), draw.lines = TRUE) &
#          scale_fill_gradientn(colours = oompaBase::redgreen(50)) & theme(text = element_text(size =8),legend.key.size = unit(.56, 'cm')))


```




